### ISSUE TITLE
Incompatiblity w/ Latest Release of GoonMod

### ISSUE THREAD

**Issue by rndash** [cjur3/GageHud#4]
Due to GoonMod updating today, GageHud is no longer compatible with GoonMod. If I attempt to run both of them together, I am no longer able to shout civilians down, bag up their bodies, and the amount of civs on the map doesn't show on the hud. If I attempt to bag up a dead civilian, the body stays there, along with the alert symbol if they had one before they died, but I am still given a body bag to hold that I cannot throw. Guards are unaffected by any of this.
There's a bit more info on the problem, along with some log info, here : https://steamcommunity.com/app/218620/discussions/15/530646080853456475/#c541907867776223592

After some testing, I've figured out that the problem only arises when "Show Civilians" is checked. Leaving it unchecked allows the game to function normally.

**Comment by rndash** [comment]
I did a bit of testing, and it seems the issue only arises if you have "Show Civilians" checked. As long as that's off, the game functions normally and GageHud can continue to be used with GoonMod.

**Comment by cjur3** [comment]
Should be fixed now :)
